/**
 * This is the schema definition for the rich text fields used for
 * for this blog studio. When you import it in schemas.js it can be
 * reused in other parts of the studio with:
 *  {
 *    name: 'someName',
 *    title: 'Some title',
 *    type: 'blockContent'
 *  }
 */
export default {
  title: 'Block Content',
  name: 'blockContent',
  type: 'array',
  of: [
    {
      title: 'Block',
      type: 'block',
      // Styles let you set what your user can mark up blocks with. These
      // correspond with HTML tags, but you can set any title or value
      // you want and decide how you want to deal with it where you want to
      // use your content.
      styles: [
        { title: 'Normal', value: 'normal' },
        { title: 'H1', value: 'h1' },
        { title: 'H2', value: 'h2' },
        { title: 'H3', value: 'h3' },
        { title: 'H4', value: 'h4' },
        { title: 'Quote', value: 'blockquote' },
      ],
      lists: [
        { title: 'Bullet', value: 'bullet' },
        { title: 'Numbered', value: 'number' },
      ],
      // Marks let you mark up inline text in the block editor.
      marks: {
        // Decorators usually describe a single property – e.g. a typographic
        // preference or highlighting by editors.
        decorators: [
          { title: 'Strong', value: 'strong' },
          { title: 'Emphasis', value: 'em' },
          { title: 'Code', value: 'code' },
        ],
        // Annotations can be any object structure – e.g. a link or a footnote.
        annotations: [
          {
            title: 'URL',
            name: 'link',
            type: 'object',
            fields: [
              {
                title: 'URL',
                name: 'href',
                type: 'url',
              },
            ],
          },
        ],
      },
    },
    {
      type: 'image',
      options: { hotspot: true },
    },
    {
      type: 'code',
      highlightedLines: [1, 2],
      options: {
        languageAlternatives: [
          { value: 'oneC', title: 'oneC' },
          { value: 'abnf', title: 'abnf' },
          { value: 'accesslog', title: 'accesslog' },
          { value: 'actionscript', title: 'actionscript' },
          { value: 'ada', title: 'ada' },
          { value: 'angelscript', title: 'angelscript' },
          { value: 'apache', title: 'apache' },
          { value: 'applescript', title: 'applescript' },
          { value: 'arcade', title: 'arcade' },
          { value: 'arduino', title: 'arduino' },
          { value: 'armasm', title: 'armasm' },
          { value: 'asciidoc', title: 'asciidoc' },
          { value: 'aspectj', title: 'aspectj' },
          { value: 'autohotkey', title: 'autohotkey' },
          { value: 'autoit', title: 'autoit' },
          { value: 'avrasm', title: 'avrasm' },
          { value: 'awk', title: 'awk' },
          { value: 'axapta', title: 'axapta' },
          { value: 'bash', title: 'bash' },
          { value: 'basic', title: 'basic' },
          { value: 'bnf', title: 'bnf' },
          { value: 'brainfuck', title: 'brainfuck' },
          { value: 'cLike', title: 'cLike' },
          { value: 'c', title: 'c' },
          { value: 'cal', title: 'cal' },
          { value: 'capnproto', title: 'capnproto' },
          { value: 'ceylon', title: 'ceylon' },
          { value: 'clean', title: 'clean' },
          { value: 'clojureRepl', title: 'clojureRepl' },
          { value: 'clojure', title: 'clojure' },
          { value: 'cmake', title: 'cmake' },
          { value: 'coffeescript', title: 'coffeescript' },
          { value: 'coq', title: 'coq' },
          { value: 'cos', title: 'cos' },
          { value: 'cpp', title: 'cpp' },
          { value: 'crmsh', title: 'crmsh' },
          { value: 'crystal', title: 'crystal' },
          { value: 'csharp', title: 'csharp' },
          { value: 'csp', title: 'csp' },
          { value: 'css', title: 'css' },
          { value: 'd', title: 'd' },
          { value: 'dart', title: 'dart' },
          { value: 'delphi', title: 'delphi' },
          { value: 'diff', title: 'diff' },
          { value: 'django', title: 'django' },
          { value: 'dns', title: 'dns' },
          { value: 'dockerfile', title: 'dockerfile' },
          { value: 'dos', title: 'dos' },
          { value: 'dsconfig', title: 'dsconfig' },
          { value: 'dts', title: 'dts' },
          { value: 'dust', title: 'dust' },
          { value: 'ebnf', title: 'ebnf' },
          { value: 'elixir', title: 'elixir' },
          { value: 'elm', title: 'elm' },
          { value: 'erb', title: 'erb' },
          { value: 'erlangRepl', title: 'erlangRepl' },
          { value: 'erlang', title: 'erlang' },
          { value: 'excel', title: 'excel' },
          { value: 'fix', title: 'fix' },
          { value: 'flix', title: 'flix' },
          { value: 'fortran', title: 'fortran' },
          { value: 'fsharp', title: 'fsharp' },
          { value: 'gams', title: 'gams' },
          { value: 'gauss', title: 'gauss' },
          { value: 'gcode', title: 'gcode' },
          { value: 'gherkin', title: 'gherkin' },
          { value: 'glsl', title: 'glsl' },
          { value: 'gml', title: 'gml' },
          { value: 'go', title: 'go' },
          { value: 'golo', title: 'golo' },
          { value: 'gradle', title: 'gradle' },
          { value: 'groovy', title: 'groovy' },
          { value: 'haml', title: 'haml' },
          { value: 'handlebars', title: 'handlebars' },
          { value: 'haskell', title: 'haskell' },
          { value: 'haxe', title: 'haxe' },
          { value: 'hsp', title: 'hsp' },
          { value: 'htmlbars', title: 'htmlbars' },
          { value: 'http', title: 'http' },
          { value: 'hy', title: 'hy' },
          { value: 'inform7', title: 'inform7' },
          { value: 'ini', title: 'ini' },
          { value: 'irpf90', title: 'irpf90' },
          { value: 'isbl', title: 'isbl' },
          { value: 'java', title: 'java' },
          { value: 'javascript', title: 'javascript' },
          { value: 'jbossCli', title: 'jbossCli' },
          { value: 'json', title: 'json' },
          { value: 'juliaRepl', title: 'juliaRepl' },
          { value: 'julia', title: 'julia' },
          { value: 'kotlin', title: 'kotlin' },
          { value: 'lasso', title: 'lasso' },
          { value: 'latex', title: 'latex' },
          { value: 'ldif', title: 'ldif' },
          { value: 'leaf', title: 'leaf' },
          { value: 'less', title: 'less' },
          { value: 'lisp', title: 'lisp' },
          { value: 'livecodeserver', title: 'livecodeserver' },
          { value: 'livescript', title: 'livescript' },
          { value: 'llvm', title: 'llvm' },
          { value: 'lsl', title: 'lsl' },
          { value: 'lua', title: 'lua' },
          { value: 'makefile', title: 'makefile' },
          { value: 'markdown', title: 'markdown' },
          { value: 'mathematica', title: 'mathematica' },
          { value: 'matlab', title: 'matlab' },
          { value: 'maxima', title: 'maxima' },
          { value: 'mel', title: 'mel' },
          { value: 'mercury', title: 'mercury' },
          { value: 'mipsasm', title: 'mipsasm' },
          { value: 'mizar', title: 'mizar' },
          { value: 'mojolicious', title: 'mojolicious' },
          { value: 'monkey', title: 'monkey' },
          { value: 'moonscript', title: 'moonscript' },
          { value: 'n1ql', title: 'n1ql' },
          { value: 'nginx', title: 'nginx' },
          { value: 'nim', title: 'nim' },
          { value: 'nix', title: 'nix' },
          { value: 'nodeRepl', title: 'nodeRepl' },
          { value: 'nsis', title: 'nsis' },
          { value: 'objectivec', title: 'objectivec' },
          { value: 'ocaml', title: 'ocaml' },
          { value: 'openscad', title: 'openscad' },
          { value: 'oxygene', title: 'oxygene' },
          { value: 'parser3', title: 'parser3' },
          { value: 'perl', title: 'perl' },
          { value: 'pf', title: 'pf' },
          { value: 'pgsql', title: 'pgsql' },
          { value: 'phpTemplate', title: 'phpTemplate' },
          { value: 'php', title: 'php' },
          { value: 'plaintext', title: 'plaintext' },
          { value: 'pony', title: 'pony' },
          { value: 'powershell', title: 'powershell' },
          { value: 'processing', title: 'processing' },
          { value: 'profile', title: 'profile' },
          { value: 'prolog', title: 'prolog' },
          { value: 'properties', title: 'properties' },
          { value: 'protobuf', title: 'protobuf' },
          { value: 'puppet', title: 'puppet' },
          { value: 'purebasic', title: 'purebasic' },
          { value: 'pythonRepl', title: 'pythonRepl' },
          { value: 'python', title: 'python' },
          { value: 'q', title: 'q' },
          { value: 'qml', title: 'qml' },
          { value: 'r', title: 'r' },
          { value: 'reasonml', title: 'reasonml' },
          { value: 'rib', title: 'rib' },
          { value: 'roboconf', title: 'roboconf' },
          { value: 'routeros', title: 'routeros' },
          { value: 'rsl', title: 'rsl' },
          { value: 'ruby', title: 'ruby' },
          { value: 'ruleslanguage', title: 'ruleslanguage' },
          { value: 'rust', title: 'rust' },
          { value: 'sas', title: 'sas' },
          { value: 'scala', title: 'scala' },
          { value: 'scheme', title: 'scheme' },
          { value: 'scilab', title: 'scilab' },
          { value: 'scss', title: 'scss' },
          { value: 'shell', title: 'shell' },
          { value: 'smali', title: 'smali' },
          { value: 'smalltalk', title: 'smalltalk' },
          { value: 'sml', title: 'sml' },
          { value: 'sqf', title: 'sqf' },
          { value: 'sql', title: 'sql' },
          { value: 'stan', title: 'stan' },
          { value: 'stata', title: 'stata' },
          { value: 'step21', title: 'step21' },
          { value: 'stylus', title: 'stylus' },
          { value: 'subunit', title: 'subunit' },
          { value: 'swift', title: 'swift' },
          { value: 'taggerscript', title: 'taggerscript' },
          { value: 'tap', title: 'tap' },
          { value: 'tcl', title: 'tcl' },
          { value: 'thrift', title: 'thrift' },
          { value: 'tp', title: 'tp' },
          { value: 'twig', title: 'twig' },
          { value: 'typescript', title: 'typescript' },
          { value: 'vala', title: 'vala' },
          { value: 'vbnet', title: 'vbnet' },
          { value: 'vbscriptHtml', title: 'vbscriptHtml' },
          { value: 'vbscript', title: 'vbscript' },
          { value: 'verilog', title: 'verilog' },
          { value: 'vhdl', title: 'vhdl' },
          { value: 'vim', title: 'vim' },
          { value: 'x86asm', title: 'x86asm' },
          { value: 'xl', title: 'xl' },
          { value: 'xml', title: 'xml' },
          { value: 'xquery', title: 'xquery' },
          { value: 'yaml', title: 'yaml' },
          { value: 'zephir', title: 'zephir' },
        ],
      },
    },
  ],
}
